services:
  training.frontend:
    image: ${DOCKER_REGISTRY-}trainingfrontend
    ports:
      - "3000:3000"
    volumes:
      - ./fe-config.json:/config.json
    depends_on:
      - trainingapi
      - training.cms

  trainingapi:
    image: ${DOCKER_REGISTRY-}trainingapi
    restart: always
    environment:
      ConnectionStrings__MyDatabase: server=trainingmysql;user id=root;password=Password@1234;database=mydb
      AutoMigration: true
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8000
      JWT_SECRET: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
      ADMIN_KEY: abcxyz_lmaolmaolmao
    ports:
      - "8000:8000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./uploads:/uploads
    depends_on:
      - trainingmysql

  training.cms:
    image: ${DOCKER_REGISTRY-}trainingcms
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__MyDatabase: server=trainingmysql;user id=root;password=Password@1234;database=mydb
      AutoMigration: true
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8000
      JWT_SECRET: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
      ADMIN_KEY: abcxyz_lmaolmaolmao
    depends_on:
      - trainingmysql
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./uploads:/uploads
    restart: always

  trainingmysql:
    environment:
      MYSQL_ROOT_PASSWORD: Password@1234
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: Password@1234
    volumes:
      - "trainingdocker_data:/var/lib/mysql"
    image: mysql
    ports:
      - "3306:3306"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      environment:
        PMA_HOST: trainingmysql
        PMA_USER: root
        PMA_PASSWORD: Password@1234
      ports:
        - "8001:80"

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://nginx:80"
      - "--url=preferably-upright-walleye.ngrok-free.app"
    environment:
      NGROK_AUTHTOKEN: 2vYjT5j40edREjK6Qbpysfr5TyK_4qhEj643Y4rxNCHoM1wPo
    ports:
      - 4040:4040

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "4444:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - training.cms
      - trainingapi
      - training.frontend

volumes:
  trainingdocker_data:
    external: true